### ISSUE TITLE
H265

### ISSUE THREAD

**Issue by wbasterfield** [D2Edev/onvifjava#1]
Profile . getVideoEncoderConfiguration()

Does not work if the camera encoding is set to H265

**Comment by D2Edev** [comment]
as far as I understand, h.265 is not included on Onvif currently, only release candidate exists (https://www.onvif.org/profiles/profile-t/). My library and the one on which it's based are built on current specifications, which do not know anything about h.265, see https://www.onvif.org/ver10/media/wsdl/media.wsdl, GetVideoEncoderConfiguration method description and respective bean VideoEncoderConfiguration described here https://www.onvif.org/ver10/schema/onvif.xsd, check Encoding field: "Used video codec, either Jpeg, H.264 or Mpeg4- enum { 'JPEG', 'MPEG4', 'H264' }"
Well, option is to use alternative bean from Media 2 extension -  VideoEncoder2Configuration which Encoding setting is not limited to fixed set of values, but currently I have no possibility to experiment with that and don't have h265 cam either...

**Comment by wbasterfield** [comment]
No problem I'll stick with H 264 for now.
